### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by BoydYang** [guardian/ganglia-api#4]
Ubuntu 14.04
Ganglia 3.6.0

No data returned from the API

**Comment by satterly** [comment]
This project is no longer in active development. However pull requests from the community to update it to work with the latest version of `gmetad` would be accepted.

**Comment by satterly** [comment]
Ensure that the `GANGLIA_PATH` is set to where your `gmetad.conf` files are located eg. `/usr/local/etc` or `/etc/ganglia`
