### ISSUE TITLE
getting empty data

### ISSUE THREAD

**Issue by ravindhar** [guardian/ganglia-api#6]
Ubuntu 14.04
Ganglia 3.7.2

No data returned from the API

**Comment by satterly** [comment]
You're going to have to give me more info. Join me on Gitter https://gitter.im/alerta/chat

**Comment by ravindhar** [comment]
http://xx.xx.xx.xx:8080/ganglia/api/v1/metrics

{"response": {"metrics": [], "status": "ok", "total": 0, "time": "0.000", "localTime": "2016-06-17T12:16:28.320797"}}

**Comment by satterly** [comment]
I've just updated it (see guardian/ganglia-api#11) so try it again now. Note that the URL has changed to `v2` ie. http://x.x.x.x:8080/ganglia/api/v2/metrics

**Comment by ravindhar** [comment]
Sure I will try thanks a lot for quick response
